#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x14706DBE1E4B4540 (fourdan@xfce.org)
#
Name     : libxcvt
Version  : 0.1.2
Release  : 2
URL      : https://www.x.org/releases/individual/lib/libxcvt-0.1.2.tar.xz
Source0  : https://www.x.org/releases/individual/lib/libxcvt-0.1.2.tar.xz
Source1  : https://www.x.org/releases/individual/lib/libxcvt-0.1.2.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: libxcvt-bin = %{version}-%{release}
Requires: libxcvt-lib = %{version}-%{release}
Requires: libxcvt-license = %{version}-%{release}
Requires: libxcvt-man = %{version}-%{release}
BuildRequires : buildreq-meson

%description
libxcvt
=======
`libxcvt` is a library providing a standalone version of the X server
implementation of the VESA CVT standard timing modelines generator.

%package bin
Summary: bin components for the libxcvt package.
Group: Binaries
Requires: libxcvt-license = %{version}-%{release}

%description bin
bin components for the libxcvt package.


%package dev
Summary: dev components for the libxcvt package.
Group: Development
Requires: libxcvt-lib = %{version}-%{release}
Requires: libxcvt-bin = %{version}-%{release}
Provides: libxcvt-devel = %{version}-%{release}
Requires: libxcvt = %{version}-%{release}

%description dev
dev components for the libxcvt package.


%package lib
Summary: lib components for the libxcvt package.
Group: Libraries
Requires: libxcvt-license = %{version}-%{release}

%description lib
lib components for the libxcvt package.


%package license
Summary: license components for the libxcvt package.
Group: Default

%description license
license components for the libxcvt package.


%package man
Summary: man components for the libxcvt package.
Group: Default

%description man
man components for the libxcvt package.


%prep
%setup -q -n libxcvt-0.1.2
cd %{_builddir}/libxcvt-0.1.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1658870215
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/libxcvt
cp %{_builddir}/libxcvt-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libxcvt/44a591f7860243fd4ae5984244433e3e1c78ba35
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cvt

%files dev
%defattr(-,root,root,-)
/usr/include/libxcvt/libxcvt.h
/usr/include/libxcvt/libxcvt_mode.h
/usr/lib64/libxcvt.so
/usr/lib64/pkgconfig/libxcvt.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxcvt.so.0
/usr/lib64/libxcvt.so.0.1.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libxcvt/44a591f7860243fd4ae5984244433e3e1c78ba35

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cvt.1
